/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /usr/local/ls6/src+data/src/freeWAIS-sf-2.0/ir/RCS/field_l.c,v 2.0.1.10 1996/01/23 15:10:07 pfeifer Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define fieldconst const
#else
#define fieldconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN field_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((field_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE fieldrestart( fieldin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct field_buffer_state *YY_BUFFER_STATE;

extern int fieldleng;
extern FILE *fieldin, *fieldout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		fieldless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the fieldless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define fieldless(n) \
	do \
		{ \
		/* Undo effects of setting up fieldtext. */ \
		*field_cp = field_hold_char; \
		field_c_buf_p = field_cp = field_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up fieldtext again */ \
		} \
	while ( 0 )

#define unput(c) fieldunput( c, fieldtext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int field_size_t;


struct field_buffer_state
	{
	FILE *field_input_file;

	char *field_ch_buf;		/* input buffer */
	char *field_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	field_size_t field_buf_size;

	/* Number of characters read into field_ch_buf, not including EOB
	 * characters.
	 */
	int field_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int field_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int field_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int field_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int field_fill_buffer;

	int field_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via fieldrestart()), so that the user can continue scanning by
	 * just pointing fieldin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE field_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER field_current_buffer


/* field_hold_char holds the character lost when fieldtext is formed. */
static char field_hold_char;

static int field_n_chars;		/* number of characters read into field_ch_buf */


int fieldleng;

/* Points to current character in buffer. */
static char *field_c_buf_p = (char *) 0;
static int field_init = 1;		/* whether we need to initialize */
static int field_start = 0;	/* start state number */

/* Flag which is used to allow fieldwrap()'s to do buffer switches
 * instead of setting up a fresh fieldin.  A bit of a hack ...
 */
static int field_did_buffer_switch_on_eof;

void fieldrestart YY_PROTO(( FILE *input_file ));

void field_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void field_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE field_create_buffer YY_PROTO(( FILE *file, int size ));
void field_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void field_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void field_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER field_flush_buffer( field_current_buffer )

YY_BUFFER_STATE field_scan_buffer YY_PROTO(( char *base, field_size_t size ));
YY_BUFFER_STATE field_scan_string YY_PROTO(( fieldconst char *str ));
YY_BUFFER_STATE field_scan_bytes YY_PROTO(( fieldconst char *bytes, int len ));

static void *field_flex_alloc YY_PROTO(( field_size_t ));
static void *field_flex_realloc YY_PROTO(( void *, field_size_t ));
static void field_flex_free YY_PROTO(( void * ));

#define field_new_buffer field_create_buffer

#define field_set_interactive(is_interactive) \
	{ \
	if ( ! field_current_buffer ) \
		field_current_buffer = field_create_buffer( fieldin, YY_BUF_SIZE ); \
	field_current_buffer->field_is_interactive = is_interactive; \
	}

#define field_set_bol(at_bol) \
	{ \
	if ( ! field_current_buffer ) \
		field_current_buffer = field_create_buffer( fieldin, YY_BUF_SIZE ); \
	field_current_buffer->field_at_bol = at_bol; \
	}

#define YY_AT_BOL() (field_current_buffer->field_at_bol)

typedef unsigned char YY_CHAR;
FILE *fieldin = (FILE *) 0, *fieldout = (FILE *) 0;
typedef int field_state_type;
extern char *fieldtext;
#define fieldtext_ptr fieldtext

static field_state_type field_get_previous_state YY_PROTO(( void ));
static field_state_type field_try_NUL_trans YY_PROTO(( field_state_type current_state ));
static int field_get_next_buffer YY_PROTO(( void ));
static void field_fatal_error YY_PROTO(( fieldconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up fieldtext.
 */
#define YY_DO_BEFORE_ACTION \
	fieldtext_ptr = field_bp; \
	fieldtext_ptr -= field_more_len; \
	fieldleng = (int) (field_cp - fieldtext_ptr); \
	field_hold_char = *field_cp; \
	*field_cp = '\0'; \
	field_c_buf_p = field_cp;

#define YY_NUM_RULES 33
#define YY_END_OF_BUFFER 34
static fieldconst short int field_accept[182] =
    {   0,
        0,    0,   34,   32,   19,   32,    1,   33,   33,    3,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,    0,
       31,    1,    1,    0,    2,    3,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   31,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   27,    7,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   26,   32,   32,   32,   32,   32,   22,

        5,    7,   32,   32,   32,   32,   32,   32,   32,   32,
       29,   32,    6,   32,   32,   32,   32,   32,   32,   32,
       23,   32,   32,    5,   32,   32,   28,   32,   32,   32,
       32,   32,    4,   32,   32,   32,   32,   32,   25,   24,
       21,   32,   32,   13,   32,   32,    9,   32,   30,    8,
       32,   32,   32,   32,   20,   32,   13,   15,   32,    9,
       32,   32,   12,   32,   32,   11,   15,   32,   18,   32,
       14,   32,   11,   32,   10,   32,   17,   32,   17,   16,
        0
    } ;

static fieldconst int field_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    6,
        6,    1,    1,    1,    7,    1,    8,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,   10,    1,   11,
        6,   12,    1,    1,   13,   14,   15,   16,   17,    1,
       18,   19,   20,    1,    1,   21,    1,   22,   23,   24,
        1,   25,   26,   27,   28,    1,    1,   29,    1,    1,
        1,    1,    1,    1,    1,    1,   30,    1,   31,   32,

       33,   34,   35,   36,   37,    1,    1,   38,   39,   40,
       41,   42,    1,   43,   44,   45,   46,    1,    1,    1,
       47,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static fieldconst int field_meta[48] =
    {   0,
        1,    2,    3,    1,    1,    2,    1,    2,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static fieldconst short int field_base[188] =
    {   0,
        0,    0,  226,    0,  227,   46,   49,  227,  217,  215,
       26,  200,  201,  203,  197,  200,  195,  200,  186,  175,
      181,  183,  171,  165,  177,  164,  175,    0,   68,  203,
        0,   59,    0,  198,  227,  196,  174,  163,  165,  168,
      170,  153,  165,  170,  173,  173,  179,  170,  164,  162,
       28,  158,  159,  141,  147,  147,   46,   20,  155,  227,
      139,  151,  149,  151,  133,  140,  147,  158,  162,  152,
      161,  151,  150,  144,  137,    0,  159,  136,  126,  121,
      132,  123,  126,  123,  124,  117,  126,  146,  119,  124,
      114,  121,  112,    0,  139,  126,  129,  129,  132,    0,

      137,    0,  108,   99,  108,  100,   99,  100,  101,   99,
        0,  126,    0,  105,   98,   89,   91,   90,  111,  114,
        0,  101,  112,    0,   91,   82,    0,   89,   93,   84,
       86,   87,    0,  109,   83,   74,   81,   85,    0,    0,
        0,   87,   75,  104,   82,  105,  101,   70,    0,    0,
       69,   96,   76,   99,    0,   72,    0,   94,   59,    0,
       67,   68,    0,   88,   66,   88,    0,   64,    0,   84,
        0,   55,    0,   38,    0,   47,   68,   56,    0,    0,
      227,   55,   81,   84,   86,   89,   92
    } ;

static fieldconst short int field_def[188] =
    {   0,
      181,    1,  181,  182,  181,  183,  184,  181,  185,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  183,  186,
      182,  184,  187,  185,  181,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  181,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,

      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
        0,  181,  181,  181,  181,  181,  181
    } ;

static fieldconst short int field_nxt[275] =
    {   0,
        4,    5,    5,    6,    7,    8,    4,    9,   10,    4,
       11,    4,    4,   12,    4,    4,    4,   13,    4,   14,
       15,    4,    4,   16,    4,   17,   18,    4,    4,    4,
        4,   19,   20,    4,    4,   21,    4,   22,   23,   24,
        4,    4,   25,   26,    4,    4,   27,   30,   30,   31,
       33,   30,   84,   30,   33,   28,   33,   37,   38,   39,
       33,   40,   85,   41,   33,   42,   33,  180,   43,   30,
       30,   31,   75,   30,   76,   30,   82,  179,  178,  177,
       83,   29,   29,   29,   32,   32,   34,   34,   34,   30,
       30,   30,   33,   33,  176,  175,  174,  173,  172,  171,

      170,  169,  168,  167,  166,  165,  164,  163,  162,  161,
      160,  159,  158,  157,  156,  155,  154,  153,  152,  151,
      150,  149,  148,  147,  146,  145,  144,  143,  142,  141,
      140,  139,  138,  137,  136,  135,  134,  133,  132,  131,
      130,  129,  128,  127,  126,  125,  124,  123,  122,  121,
      120,  119,  118,  117,  116,  115,  114,  113,  112,  111,
      110,  109,  108,  107,  106,  105,  104,  103,  102,  101,
      100,   99,   98,   97,   96,   95,   94,   93,   92,   91,
       90,   89,   88,   87,   86,   81,   80,   79,   78,   77,
       74,   73,   72,   71,   70,   69,   68,   67,   66,   65,

       64,   63,   62,   61,   36,   35,   60,   59,   58,   57,
       56,   55,   54,   53,   52,   51,   50,   49,   48,   47,
       46,   45,   44,   36,   35,  181,    3,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181
    } ;

static fieldconst short int field_chk[275] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    6,    6,    6,
        7,    6,   58,    6,    7,  182,    7,   11,   11,   11,
       32,   11,   58,   11,   32,   11,   32,  178,   11,   29,
       29,   29,   51,   29,   51,   29,   57,  177,  176,  174,
       57,  183,  183,  183,  184,  184,  185,  185,  185,  186,
      186,  186,  187,  187,  172,  170,  168,  166,  165,  164,

      162,  161,  159,  158,  156,  154,  153,  152,  151,  148,
      147,  146,  145,  144,  143,  142,  138,  137,  136,  135,
      134,  132,  131,  130,  129,  128,  126,  125,  123,  122,
      120,  119,  118,  117,  116,  115,  114,  112,  110,  109,
      108,  107,  106,  105,  104,  103,  101,   99,   98,   97,
       96,   95,   93,   92,   91,   90,   89,   88,   87,   86,
       85,   84,   83,   82,   81,   80,   79,   78,   77,   75,
       74,   73,   72,   71,   70,   69,   68,   67,   66,   65,
       64,   63,   62,   61,   59,   56,   55,   54,   53,   52,
       50,   49,   48,   47,   46,   45,   44,   43,   42,   41,

       40,   39,   38,   37,   36,   34,   30,   27,   26,   25,
       24,   23,   22,   21,   20,   19,   18,   17,   16,   15,
       14,   13,   12,   10,    9,    3,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181
    } ;

static field_state_type field_last_accepting_state;
static char *field_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int field_more_flag = 0;
static int field_more_len = 0;
#define fieldmore() (field_more_flag = 1)
#define YY_MORE_ADJ field_more_len
char *fieldtext;
#line 1 "field_l.l"
#define INITIAL 0
#line 2 "field_l.l"
/*                               -*- Mode: C -*- 
 * field_l.l -- 
 * ITIID           : $ITI$ $Header $__Header$
 * Author          : Ulrich Pfeifer
 * Created On      : Tue Feb 15 16:03:22 1994
 * Last Modified By: Ulrich Pfeifer
 * Last Modified On: Wed Dec 20 14:17:22 1995
 * Update Count    : 274
 * Status          : Unknown, Use with caution!
 */


/* HISTORY 
 * 10-Mar-1994		Ulrich Pfeifer	
 *    added support for backslash escaped '/'.
 */
#include "field_index.h"
#include "field_y.h"
#include "cutil.h"
#ifdef FLEX_SCANNER
int fieldlineno = 0;
#define UPDATELINENO if (fieldtext[0]=='\n') fieldlineno++;
#define YY_SKIP_YYWRAP
#undef fieldwrap
#define fieldwrap() (1)
#else /* not FLEX_SCANNER */
#define UPDATELINENO
#endif /* not FLEX_SCANNER */

#undef  ECHO
#define ECHO 
#line 515 "lex.field.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int fieldwrap YY_PROTO(( void ));
#else
extern int fieldwrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void fieldunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef fieldtext_ptr
static void field_flex_strncpy YY_PROTO(( char *, fieldconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int fieldinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int field_start_stack_ptr = 0;
static int field_start_stack_depth = 0;
static int *field_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void field_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void field_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int field_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( fieldtext, fieldleng, 1, fieldout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( field_current_buffer->field_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( fieldin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( fieldin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, fieldin )) == 0) \
		  && ferror( fieldin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "fieldterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef fieldterminate
#define fieldterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) field_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int fieldlex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after fieldtext and fieldleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register field_state_type field_current_state;
	register char *field_cp, *field_bp;
	register int field_act;

#line 35 "field_l.l"

#line 664 "lex.field.c"

	if ( field_init )
		{
		field_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! field_start )
			field_start = 1;	/* first start state */

		if ( ! fieldin )
			fieldin = stdin;

		if ( ! fieldout )
			fieldout = stdout;

		if ( ! field_current_buffer )
			field_current_buffer =
				field_create_buffer( fieldin, YY_BUF_SIZE );

		field_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		field_more_len = 0;
		if ( field_more_flag )
			{
			field_more_len = fieldleng;
			field_more_flag = 0;
			}
		field_cp = field_c_buf_p;

		/* Support of fieldtext. */
		*field_cp = field_hold_char;

		/* field_bp points to the position in field_ch_buf of the start of
		 * the current run.
		 */
		field_bp = field_cp;

		field_current_state = field_start;
field_match:
		do
			{
			register YY_CHAR field_c = field_ec[YY_SC_TO_UI(*field_cp)];
			if ( field_accept[field_current_state] )
				{
				field_last_accepting_state = field_current_state;
				field_last_accepting_cpos = field_cp;
				}
			while ( field_chk[field_base[field_current_state] + field_c] != field_current_state )
				{
				field_current_state = (int) field_def[field_current_state];
				if ( field_current_state >= 182 )
					field_c = field_meta[(unsigned int) field_c];
				}
			field_current_state = field_nxt[field_base[field_current_state] + (unsigned int) field_c];
			++field_cp;
			}
		while ( field_base[field_current_state] != 227 );

field_find_action:
		field_act = field_accept[field_current_state];
		if ( field_act == 0 )
			{ /* have to back up */
			field_cp = field_last_accepting_cpos;
			field_current_state = field_last_accepting_state;
			field_act = field_accept[field_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( field_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*field_cp = field_hold_char;
			field_cp = field_last_accepting_cpos;
			field_current_state = field_last_accepting_state;
			goto field_find_action;

case 1:
YY_RULE_SETUP
#line 36 "field_l.l"
{ ECHO; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 37 "field_l.l"
{ ECHO; 
	      if (fieldtext[fieldleng-2] == '\\') { 
                /* the ending '/' was escaped, lets get the rest */
                unput(fieldtext[fieldleng-1]);/* yes fieldless() is better */ 
		/* unput has backed up over the backslash, so
			thats one less character to glue back on */
		fieldleng-- ;  /* adjust for omitted backslash */
                fieldmore(); 
	      } else {
                /* Flex bug?  When there is more than one escape, the
                   call to unput adds two chars to the front of fieldtext.
                   We now skip them :-(
                   */
                /* while (*s && *s != '/') s++; */
                fieldlval.sval = s_malloc(4*strlen(fieldtext)+1); /* Space for escapes */

		{ char *s = fieldtext;
                  char *t = fieldlval.sval;
		  while (*s) { 
		    if (*s == '\\') {
                      /*  escape */
                      s++;
		      if (*s == '/') { /* escaped '/' */
			*t = *s;
		      } else if (*s == '\\') { /* double \\ */
                        *t = '\\';
		      }	else if ((*s == 'n' || *s == 'J')) {
#ifdef ESCAPE_NEWLINE
                        sprintf(t, "\\%03o", (int) '\n');
                        t+=3;
#else /* not ESCAPE_NEWLINE */
#ifdef MYREGEXP
                        *t = '\n';
#else /* not MYREGEXP */
                        *t = '$';
#endif /* not MYREGEXP */
#endif /* not ESCAPE_NEWLINE */
		      } else if (*s >= 'A' && *s <= 'Z') { 
#ifdef ESCAPE_CONTROL
                        sprintf(t, "\\%03o", (int) (*s-'A'+1));
                        t+=3;
#else /* not ESCAPE_CONTROL */
                        *t = (*s-'A'+1);
#endif /* not ESCAPE_CONTROL */
		      }	else if (*s == 'r') {
#ifdef ESCAPE_CR
                        sprintf(t, "\\%03o", (int) '\r');
                        t+=3;
#else /* not ESCAPE_CR */
                        *t = '\r';
#endif /* not ESCAPE_CR */
		      }	else if (*s == 't') {
#ifdef ESCAPE_TAB
                        sprintf(t, "\\%03o", (int) '\t');
                        t+=3;
#else /* not ESCAPE_TAB */
                        *t = '\t';
#endif /* not ESCAPE_TAB */
		      }	else if (*s == 'f') {
#ifdef ESCAPE_FORMFEED
                        sprintf(t, "\\%03o", (int) '\f');
                        t+=3;
#else /* not ESCAPE_FORMFEED */
                        *t = '\f';
#endif /* not ESCAPE_FORMFEED */
		      } else {       /* let the escaped char unmodified */
			*t = *s;
		      }
                      /* fprintf(stderr, "%c%c %c%c\n", *s, *(s+1), *t, *(t+1));*/
                      s++; t++;
		    } else {
                        /* No escape */
                        *(t++) = *(s++);
                    }
		  }
		  *t = *s; /* should be '\0' */
                  /* fprintf(stderr,"\nregexp:%s:%d %d %d %d\n", fieldlval.sval, (int)fieldlval.sval, t, (int)fieldtext, s); */
		  return(REGEXP); 
		}
	      }
	    }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 118 "field_l.l"
{ ECHO; fieldlval.ival = atoi(fieldtext); return(INT); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 119 "field_l.l"
{ ECHO; return(DATE); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 120 "field_l.l"
{ ECHO; return(DATE); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 121 "field_l.l"
{ ECHO; return(END); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 122 "field_l.l"
{ ECHO; return(END); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 123 "field_l.l"
{ ECHO; return(FIELD); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 124 "field_l.l"
{ ECHO; return(FIELD); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 125 "field_l.l"
{ ECHO; return(HEADLINE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 126 "field_l.l"
{ ECHO; return(HEADLINE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 127 "field_l.l"
{ ECHO; return(LAYOUT); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 128 "field_l.l"
{ ECHO; return(LAYOUT); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 129 "field_l.l"
{ ECHO; return(NUMERIC); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 130 "field_l.l"
{ ECHO; return(NUMERIC); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 131 "field_l.l"
{ ECHO; return(RECORD_END); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 132 "field_l.l"
{ ECHO; return(RECORD_END); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 133 "field_l.l"
{ ECHO; return(STEMMING); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 134 "field_l.l"
{ ECHO; UPDATELINENO; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 135 "field_l.l"
{ /* tung: it is very bad style to use the strings here! use a enum (up) */
                    ECHO; fieldlval.sval = strdup(fieldtext); return(ISOUNDEX); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 137 "field_l.l"
{ ECHO; fieldlval.sval = strdup(fieldtext); return(IPHONIX); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 138 "field_l.l"
{ ECHO; fieldlval.sval = strdup(fieldtext); return(ITEXT); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 139 "field_l.l"
{ ECHO; return(LOCAL); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 140 "field_l.l"
{ ECHO; return(IGNORE); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 141 "field_l.l"
{ ECHO; return(GLOBAL); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 142 "field_l.l"
{ ECHO; return(BOTH); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 143 "field_l.l"
{ ECHO; fieldlval.sval = "day"; return(DAY); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 144 "field_l.l"
{ ECHO; fieldlval.sval = "month"; return(MONTH); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 145 "field_l.l"
{ ECHO; fieldlval.sval = "year"; return(YEAR); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 146 "field_l.l"
{ ECHO; fieldlval.sval = "string";  return(STRING); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 147 "field_l.l"
{ ECHO; 
                    fieldlval.sval = strdup(fieldtext+1); 
                    fieldlval.sval[strlen(fieldlval.sval)-1] = '\0'; 
                    return(DESCRIPTION); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 151 "field_l.l"
{ ECHO; fieldlval.sval = strdup(fieldtext); return(WORD); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 152 "field_l.l"
ECHO;
	YY_BREAK
#line 1002 "lex.field.c"
case YY_STATE_EOF(INITIAL):
	fieldterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int field_amount_of_matched_text = (int) (field_cp - fieldtext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*field_cp = field_hold_char;

		if ( field_current_buffer->field_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed fieldin at a new source and called
			 * fieldlex().  If so, then we have to assure
			 * consistency between field_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			field_n_chars = field_current_buffer->field_n_chars;
			field_current_buffer->field_input_file = fieldin;
			field_current_buffer->field_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for field_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since field_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( field_c_buf_p <= &field_current_buffer->field_ch_buf[field_n_chars] )
			{ /* This was really a NUL. */
			field_state_type field_next_state;

			field_c_buf_p = fieldtext_ptr + field_amount_of_matched_text;

			field_current_state = field_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * field_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			field_next_state = field_try_NUL_trans( field_current_state );

			field_bp = fieldtext_ptr + YY_MORE_ADJ;

			if ( field_next_state )
				{
				/* Consume the NUL. */
				field_cp = ++field_c_buf_p;
				field_current_state = field_next_state;
				goto field_match;
				}

			else
				{
				field_cp = field_c_buf_p;
				goto field_find_action;
				}
			}

		else switch ( field_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				field_did_buffer_switch_on_eof = 0;

				if ( fieldwrap() )
					{
					/* Note: because we've taken care in
					 * field_get_next_buffer() to have set up
					 * fieldtext, we can now set up
					 * field_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					field_c_buf_p = fieldtext_ptr + YY_MORE_ADJ;

					field_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! field_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				field_c_buf_p =
					fieldtext_ptr + field_amount_of_matched_text;

				field_current_state = field_get_previous_state();

				field_cp = field_c_buf_p;
				field_bp = fieldtext_ptr + YY_MORE_ADJ;
				goto field_match;

			case EOB_ACT_LAST_MATCH:
				field_c_buf_p =
				&field_current_buffer->field_ch_buf[field_n_chars];

				field_current_state = field_get_previous_state();

				field_cp = field_c_buf_p;
				field_bp = fieldtext_ptr + YY_MORE_ADJ;
				goto field_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of fieldlex */


/* field_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int field_get_next_buffer()
	{
	register char *dest = field_current_buffer->field_ch_buf;
	register char *source = fieldtext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( field_c_buf_p > &field_current_buffer->field_ch_buf[field_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( field_current_buffer->field_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( field_c_buf_p - fieldtext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (field_c_buf_p - fieldtext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( field_current_buffer->field_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		field_n_chars = 0;

	else
		{
		int num_to_read =
			field_current_buffer->field_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = field_current_buffer;

			int field_c_buf_p_offset =
				(int) (field_c_buf_p - b->field_ch_buf);

			if ( b->field_is_our_buffer )
				{
				int new_size = b->field_buf_size * 2;

				if ( new_size <= 0 )
					b->field_buf_size += b->field_buf_size / 8;
				else
					b->field_buf_size *= 2;

				b->field_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					field_flex_realloc( (void *) b->field_ch_buf,
							 b->field_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->field_ch_buf = 0;

			if ( ! b->field_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			field_c_buf_p = &b->field_ch_buf[field_c_buf_p_offset];

			num_to_read = field_current_buffer->field_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&field_current_buffer->field_ch_buf[number_to_move]),
			field_n_chars, num_to_read );
		}

	if ( field_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			fieldrestart( fieldin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			field_current_buffer->field_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	field_n_chars += number_to_move;
	field_current_buffer->field_ch_buf[field_n_chars] = YY_END_OF_BUFFER_CHAR;
	field_current_buffer->field_ch_buf[field_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	fieldtext_ptr = &field_current_buffer->field_ch_buf[0];

	return ret_val;
	}


/* field_get_previous_state - get the state just before the EOB char was reached */

static field_state_type field_get_previous_state()
	{
	register field_state_type field_current_state;
	register char *field_cp;

	field_current_state = field_start;

	for ( field_cp = fieldtext_ptr + YY_MORE_ADJ; field_cp < field_c_buf_p; ++field_cp )
		{
		register YY_CHAR field_c = (*field_cp ? field_ec[YY_SC_TO_UI(*field_cp)] : 1);
		if ( field_accept[field_current_state] )
			{
			field_last_accepting_state = field_current_state;
			field_last_accepting_cpos = field_cp;
			}
		while ( field_chk[field_base[field_current_state] + field_c] != field_current_state )
			{
			field_current_state = (int) field_def[field_current_state];
			if ( field_current_state >= 182 )
				field_c = field_meta[(unsigned int) field_c];
			}
		field_current_state = field_nxt[field_base[field_current_state] + (unsigned int) field_c];
		}

	return field_current_state;
	}


/* field_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = field_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static field_state_type field_try_NUL_trans( field_state_type field_current_state )
#else
static field_state_type field_try_NUL_trans( field_current_state )
field_state_type field_current_state;
#endif
	{
	register int field_is_jam;
	register char *field_cp = field_c_buf_p;

	register YY_CHAR field_c = 1;
	if ( field_accept[field_current_state] )
		{
		field_last_accepting_state = field_current_state;
		field_last_accepting_cpos = field_cp;
		}
	while ( field_chk[field_base[field_current_state] + field_c] != field_current_state )
		{
		field_current_state = (int) field_def[field_current_state];
		if ( field_current_state >= 182 )
			field_c = field_meta[(unsigned int) field_c];
		}
	field_current_state = field_nxt[field_base[field_current_state] + (unsigned int) field_c];
	field_is_jam = (field_current_state == 181);

	return field_is_jam ? 0 : field_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void fieldunput( int c, register char *field_bp )
#else
static void fieldunput( c, field_bp )
int c;
register char *field_bp;
#endif
	{
	register char *field_cp = field_c_buf_p;

	/* undo effects of setting up fieldtext */
	*field_cp = field_hold_char;

	if ( field_cp < field_current_buffer->field_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = field_n_chars + 2;
		register char *dest = &field_current_buffer->field_ch_buf[
					field_current_buffer->field_buf_size + 2];
		register char *source =
				&field_current_buffer->field_ch_buf[number_to_move];

		while ( source > field_current_buffer->field_ch_buf )
			*--dest = *--source;

		field_cp += (int) (dest - source);
		field_bp += (int) (dest - source);
		field_n_chars = field_current_buffer->field_buf_size;

		if ( field_cp < field_current_buffer->field_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--field_cp = (char) c;


	fieldtext_ptr = field_bp;
	field_hold_char = *field_cp;
	field_c_buf_p = field_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int fieldinput()
#else
static int input()
#endif
	{
	int c;

	*field_c_buf_p = field_hold_char;

	if ( *field_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* field_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( field_c_buf_p < &field_current_buffer->field_ch_buf[field_n_chars] )
			/* This was really a NUL. */
			*field_c_buf_p = '\0';

		else
			{ /* need more input */
			fieldtext_ptr = field_c_buf_p;
			++field_c_buf_p;

			switch ( field_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( fieldwrap() )
						{
						field_c_buf_p =
						fieldtext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! field_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return fieldinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					field_c_buf_p = fieldtext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in fieldinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) field_c_buf_p;	/* cast for 8-bit char's */
	*field_c_buf_p = '\0';	/* preserve fieldtext */
	field_hold_char = *++field_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void fieldrestart( FILE *input_file )
#else
void fieldrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! field_current_buffer )
		field_current_buffer = field_create_buffer( fieldin, YY_BUF_SIZE );

	field_init_buffer( field_current_buffer, input_file );
	field_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void field_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void field_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( field_current_buffer == new_buffer )
		return;

	if ( field_current_buffer )
		{
		/* Flush out information for old buffer. */
		*field_c_buf_p = field_hold_char;
		field_current_buffer->field_buf_pos = field_c_buf_p;
		field_current_buffer->field_n_chars = field_n_chars;
		}

	field_current_buffer = new_buffer;
	field_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (fieldwrap()) processing, but the only time this flag
	 * is looked at is after fieldwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	field_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void field_load_buffer_state( void )
#else
void field_load_buffer_state()
#endif
	{
	field_n_chars = field_current_buffer->field_n_chars;
	fieldtext_ptr = field_c_buf_p = field_current_buffer->field_buf_pos;
	fieldin = field_current_buffer->field_input_file;
	field_hold_char = *field_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE field_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE field_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) field_flex_alloc( sizeof( struct field_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in field_create_buffer()" );

	b->field_buf_size = size;

	/* field_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->field_ch_buf = (char *) field_flex_alloc( b->field_buf_size + 2 );
	if ( ! b->field_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in field_create_buffer()" );

	b->field_is_our_buffer = 1;

	field_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void field_delete_buffer( YY_BUFFER_STATE b )
#else
void field_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == field_current_buffer )
		field_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->field_is_our_buffer )
		field_flex_free( (void *) b->field_ch_buf );

	field_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void field_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void field_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	field_flush_buffer( b );

	b->field_input_file = file;
	b->field_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->field_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->field_is_interactive = 0;
#else
	b->field_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void field_flush_buffer( YY_BUFFER_STATE b )
#else
void field_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->field_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->field_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->field_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->field_buf_pos = &b->field_ch_buf[0];

	b->field_at_bol = 1;
	b->field_buffer_status = YY_BUFFER_NEW;

	if ( b == field_current_buffer )
		field_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE field_scan_buffer( char *base, field_size_t size )
#else
YY_BUFFER_STATE field_scan_buffer( base, size )
char *base;
field_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) field_flex_alloc( sizeof( struct field_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in field_scan_buffer()" );

	b->field_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->field_buf_pos = b->field_ch_buf = base;
	b->field_is_our_buffer = 0;
	b->field_input_file = 0;
	b->field_n_chars = b->field_buf_size;
	b->field_is_interactive = 0;
	b->field_at_bol = 1;
	b->field_fill_buffer = 0;
	b->field_buffer_status = YY_BUFFER_NEW;

	field_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE field_scan_string( fieldconst char *str )
#else
YY_BUFFER_STATE field_scan_string( str )
fieldconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return field_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE field_scan_bytes( fieldconst char *bytes, int len )
#else
YY_BUFFER_STATE field_scan_bytes( bytes, len )
fieldconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	field_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) field_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in field_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = field_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in field_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->field_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void field_push_state( int new_state )
#else
static void field_push_state( new_state )
int new_state;
#endif
	{
	if ( field_start_stack_ptr >= field_start_stack_depth )
		{
		field_size_t new_size;

		field_start_stack_depth += YY_START_STACK_INCR;
		new_size = field_start_stack_depth * sizeof( int );

		if ( ! field_start_stack )
			field_start_stack = (int *) field_flex_alloc( new_size );

		else
			field_start_stack = (int *) field_flex_realloc(
					(void *) field_start_stack, new_size );

		if ( ! field_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	field_start_stack[field_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void field_pop_state()
	{
	if ( --field_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(field_start_stack[field_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int field_top_state()
	{
	return field_start_stack[field_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void field_fatal_error( fieldconst char msg[] )
#else
static void field_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine fieldless() so it works in section 3 code. */

#undef fieldless
#define fieldless(n) \
	do \
		{ \
		/* Undo effects of setting up fieldtext. */ \
		fieldtext[fieldleng] = field_hold_char; \
		field_c_buf_p = fieldtext + n - YY_MORE_ADJ; \
		field_hold_char = *field_c_buf_p; \
		*field_c_buf_p = '\0'; \
		fieldleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef fieldtext_ptr
#ifdef YY_USE_PROTOS
static void field_flex_strncpy( char *s1, fieldconst char *s2, int n )
#else
static void field_flex_strncpy( s1, s2, n )
char *s1;
fieldconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *field_flex_alloc( field_size_t size )
#else
static void *field_flex_alloc( size )
field_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *field_flex_realloc( void *ptr, field_size_t size )
#else
static void *field_flex_realloc( ptr, size )
void *ptr;
field_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void field_flex_free( void *ptr )
#else
static void field_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	fieldlex();
	return 0;
	}
#endif
#line 152 "field_l.l"
