/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /usr/local/ls6/src+data/src/freeWAIS-sf-2.0/ir/RCS/query_l.c,v 2.0.1.13 1996/01/31 14:48:59 pfeifer Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define queryconst const
#else
#define queryconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN query_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((query_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE queryrestart( queryin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct query_buffer_state *YY_BUFFER_STATE;

extern int queryleng;
extern FILE *queryin, *queryout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		queryless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the queryless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define queryless(n) \
	do \
		{ \
		/* Undo effects of setting up querytext. */ \
		*query_cp = query_hold_char; \
		query_c_buf_p = query_cp = query_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up querytext again */ \
		} \
	while ( 0 )

#define unput(c) queryunput( c, querytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int query_size_t;


struct query_buffer_state
	{
	FILE *query_input_file;

	char *query_ch_buf;		/* input buffer */
	char *query_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	query_size_t query_buf_size;

	/* Number of characters read into query_ch_buf, not including EOB
	 * characters.
	 */
	int query_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int query_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int query_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int query_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int query_fill_buffer;

	int query_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via queryrestart()), so that the user can continue scanning by
	 * just pointing queryin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE query_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER query_current_buffer


/* query_hold_char holds the character lost when querytext is formed. */
static char query_hold_char;

static int query_n_chars;		/* number of characters read into query_ch_buf */


int queryleng;

/* Points to current character in buffer. */
static char *query_c_buf_p = (char *) 0;
static int query_init = 1;		/* whether we need to initialize */
static int query_start = 0;	/* start state number */

/* Flag which is used to allow querywrap()'s to do buffer switches
 * instead of setting up a fresh queryin.  A bit of a hack ...
 */
static int query_did_buffer_switch_on_eof;

void queryrestart YY_PROTO(( FILE *input_file ));

void query_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void query_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE query_create_buffer YY_PROTO(( FILE *file, int size ));
void query_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void query_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void query_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER query_flush_buffer( query_current_buffer )

YY_BUFFER_STATE query_scan_buffer YY_PROTO(( char *base, query_size_t size ));
YY_BUFFER_STATE query_scan_string YY_PROTO(( queryconst char *str ));
YY_BUFFER_STATE query_scan_bytes YY_PROTO(( queryconst char *bytes, int len ));

static void *query_flex_alloc YY_PROTO(( query_size_t ));
static void *query_flex_realloc YY_PROTO(( void *, query_size_t ));
static void query_flex_free YY_PROTO(( void * ));

#define query_new_buffer query_create_buffer

#define query_set_interactive(is_interactive) \
	{ \
	if ( ! query_current_buffer ) \
		query_current_buffer = query_create_buffer( queryin, YY_BUF_SIZE ); \
	query_current_buffer->query_is_interactive = is_interactive; \
	}

#define query_set_bol(at_bol) \
	{ \
	if ( ! query_current_buffer ) \
		query_current_buffer = query_create_buffer( queryin, YY_BUF_SIZE ); \
	query_current_buffer->query_at_bol = at_bol; \
	}

#define YY_AT_BOL() (query_current_buffer->query_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *queryin = (FILE *) 0, *queryout = (FILE *) 0;
typedef int query_state_type;
extern char *querytext;
#define querytext_ptr querytext

static query_state_type query_get_previous_state YY_PROTO(( void ));
static query_state_type query_try_NUL_trans YY_PROTO(( query_state_type current_state ));
static int query_get_next_buffer YY_PROTO(( void ));
static void query_fatal_error YY_PROTO(( queryconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up querytext.
 */
#define YY_DO_BEFORE_ACTION \
	querytext_ptr = query_bp; \
	queryleng = (int) (query_cp - query_bp); \
	query_hold_char = *query_cp; \
	*query_cp = '\0'; \
	query_c_buf_p = query_cp;

#define YY_NUM_RULES 19
#define YY_END_OF_BUFFER 20
static queryconst short int query_acclist[95] =
    {   0,
       20,   16,   19,   15,   19,   16,   19,   16,   19,   14,
       19,   19,   14,   19,   16,   19,   16,   19,   16,   19,
       16,   19,   16,   19,   16,   19,   16,   19,   16,   19,
       16,   19,   16,   19,   11,   19,   10,   11,   19,    9,
       11,   19,   13,   19,   16,   16,   16,   18,   16,   16,
       17,   12,   16,   16,   16,   16,    2,   16,   16,   16,
       16,   16,   16,   16,    9,   13,   18,   17,    1,   16,
        3,   16,   16,    7,   16,   16,   16,   13,   16,   16,
       16,    6,   16,   16,   16,   16,    4,   16,   16,   16,
        5,   16,    8,   16

    } ;

static queryconst short int query_accept[78] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    4,    6,
        8,   10,   12,   13,   15,   17,   19,   21,   23,   25,
       27,   29,   31,   33,   35,   37,   40,   43,   45,   46,
       47,   47,   49,   50,   50,   52,   53,   54,   55,   56,
       57,   59,   60,   60,   61,   62,   63,   64,   65,   66,
       66,   67,   68,   69,   71,   73,   74,   75,   76,   77,
       78,   79,   79,   80,   81,   82,   83,   84,   85,   86,
       87,   89,   90,   91,   93,   95,   95
    } ;

static queryconst int query_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    5,    6,
        7,    8,    1,    1,    1,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,    1,   12,
        6,    6,    1,    1,   13,    1,    1,   14,   15,    1,
        1,    1,    1,    1,    1,    1,    1,   16,   17,   18,
        1,   19,    1,   20,    1,    1,   21,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   22,    1,    1,   23,

       24,    1,    1,   25,   26,    1,    1,   27,    1,   28,
       29,   30,    1,   31,   32,   33,   34,    1,   21,   35,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static queryconst int query_meta[36] =
    {   0,
        1,    2,    2,    1,    1,    2,    2,    1,    1,    2,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static queryconst short int query_base[84] =
    {   0,
        0,    0,   33,   34,  129,  128,  138,    0,  141,   44,
       55,  141,  141,  129,   27,   35,   40,   44,  126,   40,
      106,  103,   47,  104,  141,  141,  121,   65,    0,   77,
      127,    0,   88,  125,    0,  141,  115,  105,  107,   93,
        0,   62,  114,  101,   96,   89,   92,   86,  108,  107,
       88,  141,  141,    0,    0,  107,  141,   92,   87,   86,
      102,   85,   70,   62,   62,  141,   50,   35,   45,   20,
        0,   14,   31,    0,   28,  141,  100,  102,   37,  104,
      106,  108,  110
    } ;

static queryconst short int query_def[84] =
    {   0,
       76,    1,   77,   77,   78,   78,   76,   79,   76,   80,
       81,   76,   76,   76,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   76,   76,   76,   76,   79,   80,
       82,   79,   81,   83,   79,   76,   79,   79,   79,   79,
       79,   79,   76,   79,   79,   79,   79,   79,   76,   76,
       76,   76,   76,   79,   79,   79,   76,   79,   79,   79,
       76,   76,   79,   79,   79,   76,   79,   79,   79,   79,
       79,   79,   79,   79,   79,    0,   76,   76,   76,   76,
       76,   76,   76
    } ;

static queryconst short int query_nxt[177] =
    {   0,
        8,    9,    9,   10,   11,   12,   12,    8,    8,   13,
        8,   14,   15,    8,    8,   16,   17,   18,    8,    8,
       19,   20,    8,    8,    8,    8,    8,   21,   22,   23,
        8,   24,    8,    8,    8,   13,   13,   29,   75,   26,
       26,   75,   37,   27,   27,   31,   31,   32,   74,   31,
       31,   39,   73,   31,   38,   31,   34,   34,   41,   35,
       34,   34,   42,   40,   34,   42,   34,   44,   72,   71,
       41,   47,   45,   50,   42,   51,   56,   42,   31,   31,
       32,   70,   31,   31,   69,   56,   31,   68,   31,   34,
       34,   67,   35,   34,   34,   66,   50,   34,   51,   34,

       25,   25,   13,   13,   30,   30,   33,   33,   31,   31,
       34,   34,   61,   65,   64,   63,   62,   61,   49,   60,
       59,   55,   58,   54,   57,   55,   55,   54,   54,   53,
       52,   49,   48,   41,   46,   43,   36,   76,   28,   28,
        7,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76
    } ;

static queryconst short int query_chk[177] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,   79,   75,    3,
        4,   73,   15,    3,    4,   10,   10,   10,   72,   10,
       10,   16,   70,   10,   15,   10,   11,   11,   17,   11,
       11,   11,   18,   16,   11,   23,   11,   20,   69,   68,
       17,   23,   20,   28,   18,   28,   42,   23,   30,   30,
       30,   67,   30,   30,   65,   42,   30,   64,   30,   33,
       33,   63,   33,   33,   33,   62,   51,   33,   51,   33,

       77,   77,   78,   78,   80,   80,   81,   81,   82,   82,
       83,   83,   61,   60,   59,   58,   56,   50,   49,   48,
       47,   46,   45,   44,   43,   40,   39,   38,   37,   34,
       31,   27,   24,   22,   21,   19,   14,    7,    6,    5,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76
    } ;

static query_state_type query_state_buf[YY_BUF_SIZE + 2], *query_state_ptr;
static char *query_full_match;
static int query_lp;
#define REJECT \
{ \
*query_cp = query_hold_char; /* undo effects of setting up querytext */ \
query_cp = query_full_match; /* restore poss. backed-over text */ \
++query_lp; \
goto find_rule; \
}
#define querymore() querymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *querytext;
#line 1 "query_l.l"
#define INITIAL 0
#line 2 "query_l.l"
/*                               -*- Mode: C -*- 
 * * qyery_l.l -- 
 * ITIID           : $ITI$ $Header $__Header$
 * Author          : Ulrich Pfeifer
 * Created On      : Tue Feb 15 16:03:22 1994
 * Last Modified By: Ulrich Pfeifer
 * Last Modified On: Wed Jan 31 15:36:36 1996
 * Language        : C
 * Update Count    : 100
 * Status          : Unknown, Use with caution!
 * 
 * (C) Copyright 1995, Universität Dortmund, all rights reserved.
 * 
 * $$
 * $Log: query_l.c,v $
 * Revision 2.0.1.13  1996/01/31 14:48:59  pfeifer
 * patch63: Changed the query term weighting syntax to
 * patch63: 'Probabilistic <* 3 Indexing'.
 *
 * Revision 2.0.1.7  1996/01/23 15:11:17  pfeifer
 * patch62:
 *
 * Revision 2.0.1.6  1996/01/14 17:26:19  pfeifer
 * patch61: Numeric searches with negative numbers did not work.
 *
 * Revision 2.0.1.5  1995/12/20 13:04:13  pfeifer
 * patch57: Adapted to 'flex version 2.5.2'.
 * patch57: Numeric searches with '.' did not work.
 *
 * Revision 2.0.1.4  1995/12/06  11:02:50  pfeifer
 * patch53: Removed bad free() call (Patch from RodneyBarnett).
 *
 * Revision 2.0.1.3  1995/10/11  15:56:51  pfeifer
 * patch36: Query parser now knows about the legal character set.
 *
 * Revision 2.0.1.2  1995/10/11  10:07:33  pfeifer
 * Words are now forced to be made up of legal characters only.
 *
 * Revision 2.0.1.1  1995/10/10  18:30:44  pfeifer
 * patch33: Handling for query term weighting with '<- 99.99' as prefix
 * patch33: operator.
 *
 */

/* HISTORY 
 * 23-Mar-1994		Ulrich Pfeifer	
 *    Last Modified: Wed Mar 23 11:09:53 1994 #29 (Ulrich Pfeifer)
 *    Added flex support
 * 10-Mar-1994		Ulrich Pfeifer	
 *    Support for literal searches
 */

#include "query_y.h"
#include "cutil.h"

#undef  ECHO
#define ECHO 
/*
[Oo][Rr]
[Nn][Oo][Tt] 
*/
extern char* querybuf;

int prox_type;
int prox_value;
#ifdef PROXIMITY
static int recognize_proxy = 1;
#else /* PROXIMITY */
static int recognize_proxy = 0;
#endif /* PROXIMITY */

#ifdef FLEX_SCANNER
int querylineno = 0;
#define YY_SKIP_YYWRAP
#undef querywrap
#define querywrap() (1)

#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
                  { \
                  int c = *(querybuf++); \
                  if (c=='\n') querylineno++; \
                  result = (c == '\0') ? YY_NULL : (buf[0] = c, 1); \
                  }
#else /* not FLEX_SCANNER */
#undef input
#define input() (((querytchar=querysptr>querysbuf?U(*--querysptr):*(querybuf++))==10?(querylineno++,querytchar):querytchar)=='\0'?0:querytchar)
#endif /* not FLEX_SCANNER */
/* The '/' in WORD is necessary for very odd cases, when '/' is legal char and
   is followed by numbers in the query. Dont know if this is important enough
   to exclude '/' from beeing part of a word.
*/
#define NUMBER 1
#define QWEIGHT 2

#line 535 "lex.query.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int querywrap YY_PROTO(( void ));
#else
extern int querywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void queryunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef querytext_ptr
static void query_flex_strncpy YY_PROTO(( char *, queryconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int queryinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int query_start_stack_ptr = 0;
static int query_start_stack_depth = 0;
static int *query_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void query_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void query_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int query_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( querytext, queryleng, 1, queryout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( query_current_buffer->query_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( queryin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( queryin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, queryin )) == 0) \
		  && ferror( queryin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "queryterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef queryterminate
#define queryterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) query_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int querylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after querytext and queryleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register query_state_type query_current_state;
	register char *query_cp, *query_bp;
	register int query_act;

#line 94 "query_l.l"


#line 685 "lex.query.c"

	if ( query_init )
		{
		query_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! query_start )
			query_start = 1;	/* first start state */

		if ( ! queryin )
			queryin = stdin;

		if ( ! queryout )
			queryout = stdout;

		if ( ! query_current_buffer )
			query_current_buffer =
				query_create_buffer( queryin, YY_BUF_SIZE );

		query_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		query_cp = query_c_buf_p;

		/* Support of querytext. */
		*query_cp = query_hold_char;

		/* query_bp points to the position in query_ch_buf of the start of
		 * the current run.
		 */
		query_bp = query_cp;

		query_current_state = query_start;
		query_state_ptr = query_state_buf;
		*query_state_ptr++ = query_current_state;
query_match:
		do
			{
			register YY_CHAR query_c = query_ec[YY_SC_TO_UI(*query_cp)];
			while ( query_chk[query_base[query_current_state] + query_c] != query_current_state )
				{
				query_current_state = (int) query_def[query_current_state];
				if ( query_current_state >= 77 )
					query_c = query_meta[(unsigned int) query_c];
				}
			query_current_state = query_nxt[query_base[query_current_state] + (unsigned int) query_c];
			*query_state_ptr++ = query_current_state;
			++query_cp;
			}
		while ( query_base[query_current_state] != 141 );

query_find_action:
		query_current_state = *--query_state_ptr;
		query_lp = query_accept[query_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( query_lp && query_lp < query_accept[query_current_state + 1] )
				{
				query_act = query_acclist[query_lp];
					{
					query_full_match = query_cp;
					break;
					}
				}
			--query_cp;
			query_current_state = *--query_state_ptr;
			query_lp = query_accept[query_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( query_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 96 "query_l.l"
{ ECHO; return(AND); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 97 "query_l.l"
{ ECHO; return(OR); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 98 "query_l.l"
{ ECHO; return(NOT); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 99 "query_l.l"
{ ECHO; return(PHONIX);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 100 "query_l.l"
{ ECHO; return(SOUNDEX);}
	YY_BREAK
case 6:
*query_cp = query_hold_char; /* undo effects of setting up querytext */
query_c_buf_p = query_cp = query_bp + 4;
YY_DO_BEFORE_ACTION; /* set up querytext again */
YY_RULE_SETUP
#line 102 "query_l.l"
{
                    if (!recognize_proxy) REJECT;
                    ECHO;
                    BEGIN NUMBER;
                    prox_value = 1;   /* default value of 1 */
                    prox_type  = PROX_ORDERED;
                  }
	YY_BREAK
case 7:
*query_cp = query_hold_char; /* undo effects of setting up querytext */
query_c_buf_p = query_cp = query_bp + 2;
YY_DO_BEFORE_ACTION; /* set up querytext again */
YY_RULE_SETUP
#line 109 "query_l.l"
{
                    if (!recognize_proxy) REJECT;
                    ECHO;
                    BEGIN NUMBER;
                    prox_value = 1;   /* default value of 1 */
                    prox_type  = PROX_UNORDERED;
                  }
	YY_BREAK
case 8:
*query_cp = query_hold_char; /* undo effects of setting up querytext */
query_c_buf_p = query_cp = query_bp + 7;
YY_DO_BEFORE_ACTION; /* set up querytext again */
YY_RULE_SETUP
#line 116 "query_l.l"
{
                    if (!recognize_proxy) REJECT;
                    ECHO;
                    BEGIN NUMBER;
                    prox_value = 2;   /* default value of 2 */
                    prox_type  = PROX_ATLEAST;
                  }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 123 "query_l.l"
{ ECHO; prox_value = atoi(querytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 124 "query_l.l"
{
                    BEGIN INITIAL;	/* end of number, consume this char */
                    querylval.ival = prox_value;
                    return(prox_type);
                  }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 129 "query_l.l"
{
                    unput(querytext[0]);	/* not a number, put it back */
                    BEGIN INITIAL;
                    querylval.ival = prox_value;
                    return(prox_type);
                  }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 135 "query_l.l"
{ ECHO; BEGIN QWEIGHT; return(ASSIGN); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 136 "query_l.l"
{ 
                    ECHO; BEGIN 0; querylval.sval = s_strdup(querytext); 
                    return (FLOAT); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 139 "query_l.l"
{ ECHO; return(querytext[0]); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 140 "query_l.l"
{ ECHO; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 141 "query_l.l"
{ char *a = querytext;
                    ECHO; 
                    /* fprintf(stderr, "word?: %s\n", a); */ 
                    while (*a && (isalnum(*a) || *a == '*' || *a == '.' || *a == '-' ||  *a == '+')) {
                        a++;
                    }
                    if (*a) {
                        if (a == querytext) {
                            /* No char accepted */
                            /* fprintf(stderr, "unput: %c %s %d\n", *a, a, 1);*/
                            REJECT;
                        } else {
                            char *s = a;
                            char ch = *a;
                            /*
                            fprintf(stderr, "unput: %c %s %d\n", *a, a, 
                                    strlen(a));
                                    */
                            *a = '\0';
                            querylval.sval = s_strdup(querytext); 
                            *a = ch;
                            queryless(strlen(querylval.sval));
                            return(WORD);
                        }
                    } else {
                        /* fprintf(stderr, "word!: %s\n", a, querytext); */
                        querylval.sval = s_strdup(querytext); 
                        return(WORD);
                    }
                  }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 171 "query_l.l"
{ 
                    if (recognize_proxy) REJECT;
                    querytext[0] = '"'; querytext[queryleng-1] = '"';
	            ECHO; querylval.sval = s_strdup(querytext); return(WORD);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 175 "query_l.l"
{ 
                    if (recognize_proxy) REJECT;
                    ECHO; querylval.sval = s_strdup(querytext); return(WORD);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 178 "query_l.l"
ECHO;
	YY_BREAK
#line 936 "lex.query.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(NUMBER):
			case YY_STATE_EOF(QWEIGHT):
				queryterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int query_amount_of_matched_text = (int) (query_cp - querytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*query_cp = query_hold_char;

		if ( query_current_buffer->query_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed queryin at a new source and called
			 * querylex().  If so, then we have to assure
			 * consistency between query_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			query_n_chars = query_current_buffer->query_n_chars;
			query_current_buffer->query_input_file = queryin;
			query_current_buffer->query_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for query_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since query_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( query_c_buf_p <= &query_current_buffer->query_ch_buf[query_n_chars] )
			{ /* This was really a NUL. */
			query_state_type query_next_state;

			query_c_buf_p = querytext_ptr + query_amount_of_matched_text;

			query_current_state = query_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * query_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			query_next_state = query_try_NUL_trans( query_current_state );

			query_bp = querytext_ptr + YY_MORE_ADJ;

			if ( query_next_state )
				{
				/* Consume the NUL. */
				query_cp = ++query_c_buf_p;
				query_current_state = query_next_state;
				goto query_match;
				}

			else
				{
				query_cp = query_c_buf_p;
				goto query_find_action;
				}
			}

		else switch ( query_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				query_did_buffer_switch_on_eof = 0;

				if ( querywrap() )
					{
					/* Note: because we've taken care in
					 * query_get_next_buffer() to have set up
					 * querytext, we can now set up
					 * query_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					query_c_buf_p = querytext_ptr + YY_MORE_ADJ;

					query_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! query_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				query_c_buf_p =
					querytext_ptr + query_amount_of_matched_text;

				query_current_state = query_get_previous_state();

				query_cp = query_c_buf_p;
				query_bp = querytext_ptr + YY_MORE_ADJ;
				goto query_match;

			case EOB_ACT_LAST_MATCH:
				query_c_buf_p =
				&query_current_buffer->query_ch_buf[query_n_chars];

				query_current_state = query_get_previous_state();

				query_cp = query_c_buf_p;
				query_bp = querytext_ptr + YY_MORE_ADJ;
				goto query_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of querylex */


/* query_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int query_get_next_buffer()
	{
	register char *dest = query_current_buffer->query_ch_buf;
	register char *source = querytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( query_c_buf_p > &query_current_buffer->query_ch_buf[query_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( query_current_buffer->query_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( query_c_buf_p - querytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (query_c_buf_p - querytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( query_current_buffer->query_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		query_n_chars = 0;

	else
		{
		int num_to_read =
			query_current_buffer->query_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = query_current_buffer;

			int query_c_buf_p_offset =
				(int) (query_c_buf_p - b->query_ch_buf);

			if ( b->query_is_our_buffer )
				{
				int new_size = b->query_buf_size * 2;

				if ( new_size <= 0 )
					b->query_buf_size += b->query_buf_size / 8;
				else
					b->query_buf_size *= 2;

				b->query_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					query_flex_realloc( (void *) b->query_ch_buf,
							 b->query_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->query_ch_buf = 0;

			if ( ! b->query_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			query_c_buf_p = &b->query_ch_buf[query_c_buf_p_offset];

			num_to_read = query_current_buffer->query_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&query_current_buffer->query_ch_buf[number_to_move]),
			query_n_chars, num_to_read );
		}

	if ( query_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			queryrestart( queryin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			query_current_buffer->query_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	query_n_chars += number_to_move;
	query_current_buffer->query_ch_buf[query_n_chars] = YY_END_OF_BUFFER_CHAR;
	query_current_buffer->query_ch_buf[query_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	querytext_ptr = &query_current_buffer->query_ch_buf[0];

	return ret_val;
	}


/* query_get_previous_state - get the state just before the EOB char was reached */

static query_state_type query_get_previous_state()
	{
	register query_state_type query_current_state;
	register char *query_cp;

	query_current_state = query_start;
	query_state_ptr = query_state_buf;
	*query_state_ptr++ = query_current_state;

	for ( query_cp = querytext_ptr + YY_MORE_ADJ; query_cp < query_c_buf_p; ++query_cp )
		{
		register YY_CHAR query_c = (*query_cp ? query_ec[YY_SC_TO_UI(*query_cp)] : 1);
		while ( query_chk[query_base[query_current_state] + query_c] != query_current_state )
			{
			query_current_state = (int) query_def[query_current_state];
			if ( query_current_state >= 77 )
				query_c = query_meta[(unsigned int) query_c];
			}
		query_current_state = query_nxt[query_base[query_current_state] + (unsigned int) query_c];
		*query_state_ptr++ = query_current_state;
		}

	return query_current_state;
	}


/* query_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = query_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static query_state_type query_try_NUL_trans( query_state_type query_current_state )
#else
static query_state_type query_try_NUL_trans( query_current_state )
query_state_type query_current_state;
#endif
	{
	register int query_is_jam;

	register YY_CHAR query_c = 1;
	while ( query_chk[query_base[query_current_state] + query_c] != query_current_state )
		{
		query_current_state = (int) query_def[query_current_state];
		if ( query_current_state >= 77 )
			query_c = query_meta[(unsigned int) query_c];
		}
	query_current_state = query_nxt[query_base[query_current_state] + (unsigned int) query_c];
	*query_state_ptr++ = query_current_state;
	query_is_jam = (query_current_state == 76);

	return query_is_jam ? 0 : query_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void queryunput( int c, register char *query_bp )
#else
static void queryunput( c, query_bp )
int c;
register char *query_bp;
#endif
	{
	register char *query_cp = query_c_buf_p;

	/* undo effects of setting up querytext */
	*query_cp = query_hold_char;

	if ( query_cp < query_current_buffer->query_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = query_n_chars + 2;
		register char *dest = &query_current_buffer->query_ch_buf[
					query_current_buffer->query_buf_size + 2];
		register char *source =
				&query_current_buffer->query_ch_buf[number_to_move];

		while ( source > query_current_buffer->query_ch_buf )
			*--dest = *--source;

		query_cp += (int) (dest - source);
		query_bp += (int) (dest - source);
		query_n_chars = query_current_buffer->query_buf_size;

		if ( query_cp < query_current_buffer->query_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--query_cp = (char) c;


	querytext_ptr = query_bp;
	query_hold_char = *query_cp;
	query_c_buf_p = query_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int queryinput()
#else
static int input()
#endif
	{
	int c;

	*query_c_buf_p = query_hold_char;

	if ( *query_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* query_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( query_c_buf_p < &query_current_buffer->query_ch_buf[query_n_chars] )
			/* This was really a NUL. */
			*query_c_buf_p = '\0';

		else
			{ /* need more input */
			querytext_ptr = query_c_buf_p;
			++query_c_buf_p;

			switch ( query_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( querywrap() )
						{
						query_c_buf_p =
						querytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! query_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return queryinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					query_c_buf_p = querytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in queryinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) query_c_buf_p;	/* cast for 8-bit char's */
	*query_c_buf_p = '\0';	/* preserve querytext */
	query_hold_char = *++query_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void queryrestart( FILE *input_file )
#else
void queryrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! query_current_buffer )
		query_current_buffer = query_create_buffer( queryin, YY_BUF_SIZE );

	query_init_buffer( query_current_buffer, input_file );
	query_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void query_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void query_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( query_current_buffer == new_buffer )
		return;

	if ( query_current_buffer )
		{
		/* Flush out information for old buffer. */
		*query_c_buf_p = query_hold_char;
		query_current_buffer->query_buf_pos = query_c_buf_p;
		query_current_buffer->query_n_chars = query_n_chars;
		}

	query_current_buffer = new_buffer;
	query_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (querywrap()) processing, but the only time this flag
	 * is looked at is after querywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	query_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void query_load_buffer_state( void )
#else
void query_load_buffer_state()
#endif
	{
	query_n_chars = query_current_buffer->query_n_chars;
	querytext_ptr = query_c_buf_p = query_current_buffer->query_buf_pos;
	queryin = query_current_buffer->query_input_file;
	query_hold_char = *query_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE query_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE query_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) query_flex_alloc( sizeof( struct query_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in query_create_buffer()" );

	b->query_buf_size = size;

	/* query_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->query_ch_buf = (char *) query_flex_alloc( b->query_buf_size + 2 );
	if ( ! b->query_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in query_create_buffer()" );

	b->query_is_our_buffer = 1;

	query_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void query_delete_buffer( YY_BUFFER_STATE b )
#else
void query_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == query_current_buffer )
		query_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->query_is_our_buffer )
		query_flex_free( (void *) b->query_ch_buf );

	query_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void query_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void query_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	query_flush_buffer( b );

	b->query_input_file = file;
	b->query_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->query_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->query_is_interactive = 0;
#else
	b->query_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void query_flush_buffer( YY_BUFFER_STATE b )
#else
void query_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->query_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->query_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->query_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->query_buf_pos = &b->query_ch_buf[0];

	b->query_at_bol = 1;
	b->query_buffer_status = YY_BUFFER_NEW;

	if ( b == query_current_buffer )
		query_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE query_scan_buffer( char *base, query_size_t size )
#else
YY_BUFFER_STATE query_scan_buffer( base, size )
char *base;
query_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) query_flex_alloc( sizeof( struct query_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in query_scan_buffer()" );

	b->query_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->query_buf_pos = b->query_ch_buf = base;
	b->query_is_our_buffer = 0;
	b->query_input_file = 0;
	b->query_n_chars = b->query_buf_size;
	b->query_is_interactive = 0;
	b->query_at_bol = 1;
	b->query_fill_buffer = 0;
	b->query_buffer_status = YY_BUFFER_NEW;

	query_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE query_scan_string( queryconst char *str )
#else
YY_BUFFER_STATE query_scan_string( str )
queryconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return query_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE query_scan_bytes( queryconst char *bytes, int len )
#else
YY_BUFFER_STATE query_scan_bytes( bytes, len )
queryconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	query_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) query_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in query_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = query_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in query_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->query_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void query_push_state( int new_state )
#else
static void query_push_state( new_state )
int new_state;
#endif
	{
	if ( query_start_stack_ptr >= query_start_stack_depth )
		{
		query_size_t new_size;

		query_start_stack_depth += YY_START_STACK_INCR;
		new_size = query_start_stack_depth * sizeof( int );

		if ( ! query_start_stack )
			query_start_stack = (int *) query_flex_alloc( new_size );

		else
			query_start_stack = (int *) query_flex_realloc(
					(void *) query_start_stack, new_size );

		if ( ! query_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	query_start_stack[query_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void query_pop_state()
	{
	if ( --query_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(query_start_stack[query_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int query_top_state()
	{
	return query_start_stack[query_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void query_fatal_error( queryconst char msg[] )
#else
static void query_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine queryless() so it works in section 3 code. */

#undef queryless
#define queryless(n) \
	do \
		{ \
		/* Undo effects of setting up querytext. */ \
		querytext[queryleng] = query_hold_char; \
		query_c_buf_p = querytext + n - YY_MORE_ADJ; \
		query_hold_char = *query_c_buf_p; \
		*query_c_buf_p = '\0'; \
		queryleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef querytext_ptr
#ifdef YY_USE_PROTOS
static void query_flex_strncpy( char *s1, queryconst char *s2, int n )
#else
static void query_flex_strncpy( s1, s2, n )
char *s1;
queryconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *query_flex_alloc( query_size_t size )
#else
static void *query_flex_alloc( size )
query_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *query_flex_realloc( void *ptr, query_size_t size )
#else
static void *query_flex_realloc( ptr, size )
void *ptr;
query_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void query_flex_free( void *ptr )
#else
static void query_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	querylex();
	return 0;
	}
#endif
#line 178 "query_l.l"

